Repository hibit-team/hibit-backend, pull requests merged in 2023-08, with the labels that each got.

#45 [소셜 로그인] 리프레시 토큰을 발급하는 과정에서 에러 해결
  src/main/java/com/hibit2/hibit2/auth/domain/OAuthToken.java
Labels: 버그 수정

#49 [refactor] 프로필 등록에 대한 에러 해결 및 프로필 전체 기능에 대한 리팩터링
  src/main/java/com/hibit2/hibit2/profile/controller/ProfileController.java
  src/main/java/com/hibit2/hibit2/profile/domain/Profile.java
  src/main/java/com/hibit2/hibit2/profile/domain/ProfileImage.java
  src/main/java/com/hibit2/hibit2/profile/dto/request/ProfileRegisterRequest.java
  src/main/java/com/hibit2/hibit2/profile/dto/request/ProfileUpdateRequest.java
  src/main/java/com/hibit2/hibit2/profile/dto/response/ProfileRegisterResponse.java
  src/main/java/com/hibit2/hibit2/profile/dto/response/ProfileResponse.java
  src/main/java/com/hibit2/hibit2/profile/dto/response/ProfilesResponse.java
  src/main/java/com/hibit2/hibit2/profile/service/ProfileService.java
  src/main/java/com/hibit2/hibit2/profile/support/ProfileAuthenticationPrincipal.java
  src/main/java/com/hibit2/hibit2/profile/support/ProfileAuthenticationPrincipalArgumentResolver.java
Labels: 리팩토링, 버그 수정

#60 feat: HttpOnly 쿠키방식을 이용하여 refreshToken 발급하는 기능 구현
  src/main/java/com/hibit2/hibit2/auth/presentation/AuthController.java
Labels: 기능 추가, 보안

#61 [feat] 회원가입할때 구글로부터 닉네임, 프로필 이미지를 가져오도록 구현
  src/main/java/com/hibit2/hibit2/auth/dto/OAuthMember.java
  src/main/java/com/hibit2/hibit2/global/config/properties/GoogleProperties.java
  src/main/java/com/hibit2/hibit2/infrastructure/oauth/client/GoogleOAuthClient.java
  src/main/java/com/hibit2/hibit2/infrastructure/oauth/dto/UserInfo.java
  src/main/java/com/hibit2/hibit2/member/domain/Member.java
  src/main/java/com/hibit2/hibit2/member/dto/MemberResponse.java
  src/test/java/com/hibit2/hibit2/common/Constants.java
  src/test/java/com/hibit2/hibit2/common/OAuthFixtures.java
  src/test/java/com/hibit2/hibit2/common/annotation/ServiceTest.java
  src/test/java/com/hibit2/hibit2/common/builder/GivenBuilder.java
  src/test/java/com/hibit2/hibit2/common/fixtures/MemberFixtures.java
  src/test/java/com/hibit2/hibit2/member/domain/MemberRepositoryTest.java
  src/test/java/com/hibit2/hibit2/member/domain/MemberTest.java
  src/test/java/com/hibit2/hibit2/member/service/MemberServiceTest.java
  src/test/java/com/hibit2/hibit2/profile/domain/ProfileTest.java
Labels: 리팩토링, 기능 추가

#62 [docs] 리드미를 수정(최신화)한다.
  README.md
  docs/readme/hibit-backend_stack.png
  docs/readme/hibit-frontend_stack.png
  docs/readme/hibit-git-flow.png
  docs/readme/hibit-logo-bg.png
  docs/readme/hibit-team-culture.png
  docs/readme/hibit_infra_stack.png
  docs/readme/hj-profile.jpg
  docs/readme/jaemok-profile-img.jpg
  docs/readme/minsung-profile-img.jpg
  docs/readme/pc_alarm_popup_1.png
  docs/readme/pc_alarm_popup_2.png
  docs/readme/pc_matching_board.png
  docs/readme/pc_matching_board_in.png
  docs/readme/pc_other_profile_not_register_profile.png
  docs/readme/pc_other_profile_register_profile.png
  docs/readme/pc_signup.png
Labels: 문서 작성, 디자인

#63 [FIX] user를 소셜로그인 member 테이블로 변경한다.
  src/main/java/com/hibit2/hibit2/alarm/controller/AlarmController.java
  src/main/java/com/hibit2/hibit2/alarm/controller/AlarmScheduler.java
  src/main/java/com/hibit2/hibit2/alarm/domain/Alarm.java
  src/main/java/com/hibit2/hibit2/alarm/dto/AlarmListDto.java
  src/main/java/com/hibit2/hibit2/alarm/repository/AlarmRepository.java
  src/main/java/com/hibit2/hibit2/alarm/service/AlarmService.java
  src/main/java/com/hibit2/hibit2/auth/domain/OAuthTokenRepository.java
  src/main/java/com/hibit2/hibit2/comment/controller/CommentController.java
  src/main/java/com/hibit2/hibit2/comment/domain/Comment.java
  src/main/java/com/hibit2/hibit2/comment/dto/CommentListDto.java
  src/main/java/com/hibit2/hibit2/comment/service/CommentService.java
  src/main/java/com/hibit2/hibit2/declaration/controller/DeclarationController.java
  src/main/java/com/hibit2/hibit2/declaration/domain/Declaration.java
  src/main/java/com/hibit2/hibit2/declaration/service/DeclarationService.java
  src/main/java/com/hibit2/hibit2/global/controller/SetupController.java
  src/main/java/com/hibit2/hibit2/matching/controller/MatchingController.java
  src/main/java/com/hibit2/hibit2/matching/domain/Matching.java
  src/main/java/com/hibit2/hibit2/matching/repository/MatchingRepository.java
  src/main/java/com/hibit2/hibit2/matching/service/MatchingService.java
  src/main/java/com/hibit2/hibit2/member/domain/Member.java
  src/main/java/com/hibit2/hibit2/member/dto/MemberListDto.java
  src/main/java/com/hibit2/hibit2/member/repository/MemberRepository.java
  src/main/java/com/hibit2/hibit2/post/controller/PostController.java
  src/main/java/com/hibit2/hibit2/post/domain/Post.java
  src/main/java/com/hibit2/hibit2/post/dto/PostResponseDto.java
  src/main/java/com/hibit2/hibit2/post/dto/PostSaveDto.java
  src/main/java/com/hibit2/hibit2/post/service/PostService.java
  src/main/java/com/hibit2/hibit2/postHistory/domain/postHistory.java
  src/main/java/com/hibit2/hibit2/profile/service/ProfileService.java
Labels: 리팩토링

#65 [feat] 리프레시 토큰은 set-cookie로 설정하고 사용자 id값과 프로필 등록 여부에 대한 값을 추가
  src/main/java/com/hibit2/hibit2/auth/application/AuthService.java
  src/main/java/com/hibit2/hibit2/auth/application/AuthTokenCreator.java
  src/main/java/com/hibit2/hibit2/auth/application/AuthTokenResponseHandler.java
  src/main/java/com/hibit2/hibit2/auth/application/JwtTokenProvider.java
  src/main/java/com/hibit2/hibit2/auth/application/TokenCreator.java
  src/main/java/com/hibit2/hibit2/auth/domain/AuthAccessToken.java
  src/main/java/com/hibit2/hibit2/auth/domain/AuthToken.java
  src/main/java/com/hibit2/hibit2/auth/domain/OAuthTokenRepository.java
  src/main/java/com/hibit2/hibit2/auth/dto/response/AccessAndRefreshTokenResponse.java
  src/main/java/com/hibit2/hibit2/auth/dto/response/AccessTokenResponse.java
  src/main/java/com/hibit2/hibit2/auth/exception/InvalidTokenException.java
  src/main/java/com/hibit2/hibit2/auth/presentation/AuthController.java
  src/main/java/com/hibit2/hibit2/global/token/Login.java
  src/main/java/com/hibit2/hibit2/member/controller/MemberController.java
  src/main/java/com/hibit2/hibit2/profile/repository/ProfileRepository.java
  src/test/java/com/hibit2/hibit2/auth/service/AuthServiceTest.java
  src/test/java/com/hibit2/hibit2/common/annotation/ServiceTest.java
Labels: 리팩토링, 기능 추가, 보안

#67 [feat] 프로필 전체 API에 대한 리팩터링 구현
  src/main/java/com/hibit2/hibit2/profile/controller/ProfileController.java
  src/main/java/com/hibit2/hibit2/profile/domain/AddressDistrict.java
  src/main/java/com/hibit2/hibit2/profile/domain/PersonalityType.java
  src/main/java/com/hibit2/hibit2/profile/domain/Profile.java
  src/main/java/com/hibit2/hibit2/profile/dto/request/ProfileRegisterRequest.java
  src/main/java/com/hibit2/hibit2/profile/dto/request/ProfileUpdateRequest.java
  src/main/java/com/hibit2/hibit2/profile/dto/response/ProfileOtherResponse.java
  src/main/java/com/hibit2/hibit2/profile/exception/InvalidPersonalityException.java
  src/main/java/com/hibit2/hibit2/profile/exception/InvalidProfileInfoException.java
  src/main/java/com/hibit2/hibit2/profile/exception/NicknameAlreadyTakenException.java
  src/main/java/com/hibit2/hibit2/profile/exception/NotFoundPersonalityException.java
  src/main/java/com/hibit2/hibit2/profile/repository/ProfileRepository.java
  src/main/java/com/hibit2/hibit2/profile/service/ProfileService.java
Labels: 리팩토링, 기능 추가, 버그 수정

#69 타인 프로필 API 부분에 대한 에러 해결
  src/main/java/com/hibit2/hibit2/profile/controller/ProfileController.java
  src/main/java/com/hibit2/hibit2/profile/dto/response/ProfileOtherResponse.java
  src/main/java/com/hibit2/hibit2/profile/dto/response/ProfileResponse.java
  src/main/java/com/hibit2/hibit2/profile/exception/InvalidOtherProfileException.java
  src/main/java/com/hibit2/hibit2/profile/service/ProfileService.java
Labels: 리팩토링, 버그 수정

#70 [Fix] 게시글 및 댓글 유저 권한 제한
  src/main/java/com/hibit2/hibit2/comment/controller/CommentController.java
  src/main/java/com/hibit2/hibit2/post/controller/PostController.java
Labels: 기능 추가
